2021-05-30 12:34:38,601 ERROR: Exception on /index [GET] [in c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\routes.py", line 28, in index
    deepspeechlogs = DeepSpeechLog.query.order_by(DeepSpeechLog.timestamp.desc()).paginate(
AttributeError: 'Pagination' object has no attribute 'all'
2021-05-30 12:34:39,630 ERROR: Exception on /index [GET] [in c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\routes.py", line 28, in index
    deepspeechlogs = DeepSpeechLog.query.order_by(DeepSpeechLog.timestamp.desc()).paginate(
AttributeError: 'Pagination' object has no attribute 'all'
2021-05-30 12:34:43,935 ERROR: Exception on /index [GET] [in c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\routes.py", line 28, in index
    deepspeechlogs = DeepSpeechLog.query.order_by(DeepSpeechLog.timestamp.desc()).paginate(
AttributeError: 'Pagination' object has no attribute 'all'
2021-05-30 12:34:45,547 ERROR: Exception on /index [GET] [in c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\routes.py", line 28, in index
    deepspeechlogs = DeepSpeechLog.query.order_by(DeepSpeechLog.timestamp.desc()).paginate(
AttributeError: 'Pagination' object has no attribute 'all'
2021-05-30 12:34:58,413 ERROR: Exception on /index [GET] [in c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\routes.py", line 28, in index
    deepspeechlogs = DeepSpeechLog.query.order_by(DeepSpeechLog.timestamp.desc()).paginate(
AttributeError: 'Pagination' object has no attribute 'all'
2021-05-30 12:35:00,542 ERROR: Exception on /index [GET] [in c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "c:\users\stella\documents\hochschule_\bachelorarbeit\berta\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\routes.py", line 28, in index
    deepspeechlogs = DeepSpeechLog.query.order_by(DeepSpeechLog.timestamp.desc()).paginate(
AttributeError: 'Pagination' object has no attribute 'all'
2021-05-30 12:35:59,826 INFO: Berta voice assistant [in C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\__init__.py:31]
2021-05-30 12:55:50,881 INFO: Berta voice assistant [in C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\__init__.py:31]
2021-05-30 12:57:34,628 INFO: Berta voice assistant [in C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\__init__.py:31]
2021-05-30 13:14:13,931 INFO: Berta voice assistant [in C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\__init__.py:33]
2021-05-30 13:17:18,963 INFO: Berta voice assistant [in C:\Users\Stella\Documents\Hochschule_\Bachelorarbeit\berta\app\__init__.py:33]
